module.exports = {
  content: [
      './site/templates/**/*.gohtml'
  ],
  theme: {
    fontFamily: {
      'sans': ['Montserrat'],
      'mono': ['Inconsolata']
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'black': '#000',
      'white': '#fff',
      'gray': {
        100: '#cdd6f4',
        200: '#a6adc8',
        300: '#9399b2',
        400: '#6c7086',
        500: '#585b70',
        600: '#313244',
        700: '#1E1E2E',
        800: '#181825',
        900: '#11111b',
      },
      'flamingo': '#F2CDCD',
      'mauve':    '#cba6f7',
      'pink':     '#F5C2E7',
      'maroon':   '#eba0ac',
      'red':      '#f38ba8',
      'peach':    '#fab387',
      'yellow':   '#f9e2af',
      'green':    '#a6e3a1',
      'teal':     '#94e2d5',
      'blue':     '#89b4fa',
      'sky':      '#89dceb',
    },
    screens: {
      'sm-y': {'raw': '(min-height: 390px)'},
      'md-y': {'raw': '(min-height: 778px)'},
      'xs': '382px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      spacing: {
        '26': '6.5rem',
      },
      aspectRatio: {
        'golden-y': '1 / 1.618',
        'golden-x': '1.618 / 1',
      },
      typography: (theme) => ({
        catppuccin: {
          css: {
            '--tw-prose-body': theme('colors.gray[100]'),
            '--tw-prose-headings': theme('colors.gray[100]'),
            '--tw-prose-lead': theme('colors.gray[100]'),
            '--tw-prose-links': theme('colors.blue'),
            '--tw-prose-bold': theme('colors.white'),
            '--tw-prose-counters': theme('colors.gray[100]'),
            '--tw-prose-bullets': theme('colors.gray[100]'),
            '--tw-prose-hr': theme('colors.gray[100]'),
            '--tw-prose-quotes': theme('colors.gray[100]'),
            '--tw-prose-quote-borders': theme('colors.sky'),
            '--tw-prose-captions': theme('colors.gray[100]'),
            '--tw-prose-code': theme('colors.gray[100]'),
            '--tw-prose-pre-code': theme('colors.gray[100]'),
            '--tw-prose-pre-bg': theme('colors.gray[800]'),
            '--tw-prose-th-borders': theme('colors.gray[100]'),
            '--tw-prose-td-borders': theme('colors.gray[100]'),
            '--tw-prose-invert-body': theme('colors.gray[100]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.gray[100]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.gray[100]'),
            '--tw-prose-invert-bullets': theme('colors.gray[100]'),
            '--tw-prose-invert-hr': theme('colors.gray[100]'),
            '--tw-prose-invert-quotes': theme('colors.gray[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.gray[100]'),
            '--tw-prose-invert-captions': theme('colors.gray[100]'),
            '--tw-prose-invert-code': theme('colors.gray[100]'),
            '--tw-prose-invert-pre-code': theme('colors.gray[100]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.gray[100]'),
            '--tw-prose-invert-td-borders': theme('colors.gray[100]'),
          },
        },
      })

    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
